import { ShopItem } from '../types'

export const SHOP_ITEMS: ShopItem[] = [
  { id: '1', name: 'Sonny Angel', price: 12.99, image: '/Items/sonny.png' },
  { id: '2', name: 'Aritzia Hoodie', price: 120.99, image: '/Items/AritziaHoodie.png'},
  { id: '3', name: '1 Year of 𝕏 Premium ', price: 96.99, image: '/Items/Xpremium.png' },
  { id: '4', name: 'Hermès Birkin Bag', price: 45000.99, image: '/Items/BirkinBag.png' },
  { id: '5', name: 'Steam Deck', price: 549.99, image: '/Items/SteamDeck.png' },
  { id: '6', name: 'Pizza Slice', price: 3.99, image: '/Items/pizzaslice.png' },
  { id: '7', name: 'Spot®', price: 74900.99, image: '/Items/robotDog.png' },
  { id: '8', name: 'Airpods', price: 249.99, image: '/Items/airpods.png' },
  { id: '9', name: 'iPhone 16', price: 999.99, image: '/Items/iphone.png' },
  { id: '10', name: 'Gorilla', price: 2500.99, image: '/Items/gorilla.png' },
  { id: '11', name: 'Goose Farm', price: 125000.99, image: '/Items/goosefarm.png' },
  { id: '12', name: 'Porsche', price: 95000.99, image: '/Items/porsche.png' },
  { id: '13', name: 'Single Family Home', price: 450000.99, image: '/Items/house.png' },
  { id: '14', name: 'Trip to Japan', price: 3500.99, image: '/Items/Japan.png' },
  { id: '15', name: 'Ford F1-50', price: 45000.99, image: '/Items/Ford F150.png' },
  { id: '16', name: 'Sign Lebron James', price: 2500000.99, image: '/Items/lebronjames.png' },
  { id: '17', name: 'Chanel Glasses', price: 850.99, image: '/Items/chanelglasses.png' },
  { id: '18', name: 'Tiffany & Co. Ring', price: 15000.99, image: '/Items/tiffanyRing.png' },
  { id: '19', name: 'Unlimited Nobu', price: 50000.99, image: '/Items/Nobu.png' },
  { id: '20', name: 'Drake Feature', price: 250000.99, image: '/Items/Drake.png' },
  { id: '21', name: 'Matcha Latte', price: 6.99, image: '/Items/matcha.png' },
  { id: '22', name: 'Hire Rico Jackson', price: 110.99, image: '/Items/Rico.png' },
  { id: '23', name: 'Pibble', price: 1299.99, image: '/Items/pibble.png' },
  { id: '24', name: '1st Edition Charizard', price: 8500.99, image: '/Items/charizard.png' },
  { id: '25', name: 'Tesla Cybertruck', price: 38990.99, image: '/Items/Cybertruck.png' },
  { id: '26', name: 'Dinosaur Fossil', price: 250000.99, image: '/Items/dinosaur.png' },
  { id: '27', name: 'Private Jet', price: 1500000.99, image: '/Items/jet.png'},
  { id: '28', name: 'Yacht', price: 5000000.99, image: '/Items/yacht.png' },
  { id: '29', name: 'Island', price: 10000000.99, image: '/Items/island.png' },
  { id: '30', name: 'Trip to Space ', price: 55000000.99, image: '/Items/Spaceship.png' },
  { id: '31', name: 'Movie W/ Leonardo', price: 20000000.99, image: '/Items/leonardo.png' },
].sort((a, b) => a.price - b.price)
